### ISSUE TITLE
Move deployment environments to ConfigMap

### ISSUE THREAD

**Issue by huseyindeniz** [huseyindeniz/gitops-lab#5]
Currently, the following deployment environments are stored in a local tfvars file:

- stag-1
- stag-2
- prod-blueegreen
- prod-canary

To improve manageability, move these environments to a new ConfigMap resource. Additionally, enhance the environment data to include more details. The current name field is insufficient; consider the following properties as a starting point:

- name (string)
- inUse (boolean)
- type (prod|staging)

It could be like this:

Define the ConfigMap

```tf
resource "kubernetes_config_map" "deployment_environments" {
  metadata {
    name = "deployment-environments-prod"
    namespace = "default"
  }

  data = {
    environments = jsonencode([
      {
        name   = "prod-bluegreen"
        type   = "prod"
        inUse  = false
      },
      {
        name   = "prod-canary"
        type   = "prod"
        inUse  = false
      }
    ])
  }
}

```

Parse ConfigMap Data
```tf
data "kubernetes_config_map" "deployment_environments" {
  metadata {
    name      = kubernetes_config_map.deployment_environments.metadata[0].name
    namespace = "default"
  }
}

locals {
  envs = jsondecode(data.kubernetes_config_map.deployment_environments.data["environments"])
}
```

Using it in other resources will be like this:

```tf
resource "example_resource" "example" {
  for_each = { for env in local.envs : env.name => env if env.type == "prod" }

  name   = each.value.name
  in_use = each.value.inUse
}
```

And using it in application set will be like this: (theoretically)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-001-weather-forecast-appset-prod
  namespace: argo-cd-local
spec:
  generators:
    - merge:
        generators:
          # ConfigMap generator to pull environment data
          - configMap:
              name: deployment-environments
          # List generator for environment-specific additional data
          - list:
              elements:
                - name: prod-bluegreen
                  servicePort: 6001
                  servicePreviewPort: 6002
                  host: "wf-prod-bg.local"
                  strategy: "bluegreen" # standard, bluegreen, canary
                  imgTag: '20241114182338' # {"$imagepolicy": "flux-system:weather-forecast-prod-bluegreen-app-image-policy:tag"}
                  imgMigrationTag: '20241114182250' # {"$imagepolicy": "flux-system:weather-forecast-prod-bluegreen-migration-image-policy:tag"}
                  migrationAction: 'apply' # apply, reset, rollback
                - name: prod-canary
                  servicePort: 6003
                  servicePreviewPort: 6004
                  host: "wf-prod-canary.local"
                  strategy: "canary" # standard, bluegreen, canary
                  imgTag: '20241114193704' # {"$imagepolicy": "flux-system:weather-forecast-prod-canary-app-image-policy:tag"}
                  imgMigrationTag: '20241114193621' # {"$imagepolicy": "flux-system:weather-forecast-prod-canary-migration-image-policy:tag"}
                  migrationAction: 'apply' # apply, reset, rollback
  template:
    metadata:
      name: 'weather-forecast-{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/huseyindeniz/cicd-lab.git
        targetRevision: main
        path: 'helm-charts/dotnet-core-webapi'
        helm:
          valueFiles:
            - values.yaml
            - $valuesRef/flux/local/applications/project-001/values/wf-prod-values.yaml
          valuesObject:
            environment: '{{ .name }}'
            strategy: '{{ .strategy }}'
            service:
              port: '{{ .servicePort }}'
              previewPort: '{{ .servicePreviewPort }}'
            ingress:
              host: '{{ .host }}'
            image:
              tag: '{{ .imgTag }}'
            migration:
              tag: '{{ .imgMigrationTag }}'
              action: "{{ .migrationAction }}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'project-001-weather-forecast-{{ .name }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        retry:
          limit: 1
        syncOptions:
          - SkipHooksOnError=true
```
